스와이프수정및랜덤카드수정
egomogo/front-end pull request #17
Opened 2023-07-24 12:59 UTC by Choeseonjeong

![image](https://github.com/egomogo/front-end/assets/128480236/3ab2b0a0-f2fc-47c6-8496-eecae4096643)
![image](https://github.com/egomogo/front-end/assets/128480236/bf75a8f9-0e78-4e93-85ef-622b8b612173)
거리, 하트를 식당 이름 위로 배치했습니다.

![image](https://github.com/egomogo/front-end/assets/128480236/2b963259-172e-45a0-a1cf-e4e761ecba6d)
메뉴를 추가했더니 지도가 색칠한 영역의 크기로 나와서 카드의 크기를 조금 키웠습니다.
상단의 로고를 클릭하면 home으로 가도록 했습니다. 

![랜덤카드 (1)](https://github.com/egomogo/front-end/assets/128480236/f7af42e9-f045-4971-97a1-9974e9286b26)
스와이프도 수정했는데 혹시 넘길 때 카드가 원 상태로 돌아가고 난 후에 다음 카드로 넘어가는 것이 좋을까요? 
아니면 지금도 괜찮은가요?

2023-07-24 13:07 UTC, 2hanbyeol1 commented
상세보기 상태인 카드를 넘겼을 때
기본 상태로 돌아간 후 넘어가는 것과
넘어간 후에 기본 상태가 되는 것 중
어떤 것이 낫냐는 말씀이신가요??

2023-07-24 13:09 UTC, Choeseonjeong commented
넵넵

2023-07-24 14:06 UTC, 2hanbyeol1 requested changes
1. 첫번째 RandomCard를 오른쪽으로 밀면(->, 이전 카드 제스처) 다음 카드가 나옴.
- 안 움직이도록 해야할 것 같아요

2. 제 기기에서는 양쪽에 카드 자투리?가 안 보여요.. 왜 이럴까요ㅠㅠ
<img width=200 src='https://github.com/egomogo/front-end/assets/78421872/da6bd60f-e61a-4b21-a9f3-8bc40da97188'/>

- 사용자 입장에서 밀면 다음 카드가 나올 거라는 느낌이 안 듭니다

3. 이건 중요한건 아닌데 스윽 밀면 너무 많은 카드가 넘어가는게 조금 불편할 것 같아요. 한번에 하나씩만 밀렸으면 좋겠는데 어려우면 안해도 될 것 같아요.

2023-07-24 14:06 UTC, 2hanbyeol1 commented on package.json
React-native-slider는 더 이상 사용하지 않으시는 것 같은데 지우는게 좋을 것 같아요

그 외에도 안 쓰시는거 지워주세용

2023-07-24 14:06 UTC, 2hanbyeol1 commented on src/screens/RandomBox.js
> +        onMomentumScrollEnd={() =>
이 코드는 왜 넣은건가요??
마지막 카드를 넘기면 갑자기 상세 정보 상태로 바뀌는데 어색한 것 같아요

2023-07-24 14:07 UTC, 2hanbyeol1 commented
> 넵넵

전 둘 다 나쁘지 않은 것 같아요👍

2023-07-28 03:56 UTC, Choeseonjeong commented
수정햇습니다

2023-07-29 10:49 UTC, 2hanbyeol1 reviewed
실행 잘 되는 것은 확인했습니다!! 👍

근데 코드 중에
`const newIndex = Math.round(value / (itemWidth + cardMargin));`
이 코드는 어떤 의미인가요?
index랑 width, margin이 어떤 관계가 있는 건가요??

2023-07-29 10:49 UTC, 2hanbyeol1 commented on src/screens/RandomBox.js
> +              width: itemWidth + (index === 0 ? cardMargin : cardMargin),
`width: itemWidth + (index === 0 ? cardMargin : cardMargin)`이면

**`width: itemWidth + cardMargin ` 로 고쳐도 될 것 같습니다.**
(index === 0가 True든 False든 cardMargin이니까요)

2023-07-29 11:47 UTC, 2hanbyeol1 approved these changes
👍

2023-07-29 11:49 UTC, merged